export declare const keywordMap: {
    diffuse: string;
    roughness: string;
    metalness: string;
    emissive: string;
    ao: string;
    bump: string;
    fragNormal: string;
    clearcoat: string;
    clearcoatRoughness: string;
    clearcoatNormal: string;
    transmission: string;
    thickness: string;
    iridescence: string;
    pointSize: string;
    fragColor: string;
    depthAlpha: string;
    unlitFac: string;
    position: string;
    positionRaw: string;
    normal: string;
};
